# Generated by Django 4.2.6 on 2023-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colors", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderhistory",
            name="word",
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="blue",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="green",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="red",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="orderhistory",
            name="yellow",
            field=models.IntegerField(default=None),
        ),
    ]
