# Generated by Django 4.2.6 on 2023-10-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("colors", "0002_remove_orderhistory_word_orderhistory_blue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderhistory",
            name="blue",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="green",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="red",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="orderhistory",
            name="yellow",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
